### ISSUE TITLE
Error on examples

### ISSUE THREAD

**Issue by nalo26** [twoolie/NBT#132]
Hello !

I'm trying to make the example program `block_analysis` works, but it doesn't. I saw the [other error report](https://github.com/twoolie/NBT/issues/130), but it still doesn't work in 1.13.2.
```
Parsing region r.-1.-1.mca...
Traceback (most recent call last):
  File "test.py", line 144, in <module>
    sys.exit(main(world_folder, start, stop))
  File "test.py", line 115, in main
    process_region_file(region, start, stop)
  File "test.py", line 73, in process_region_file
    for c in region.iter_chunks_class():
AttributeError: 'RegionFile' object has no attribute 'iter_chunks_class'
```

I tried to replace `iter_chunks_class` with `iter_chunks` but, I then get the following error on the next line, which I do not understand :/
```
Parsing region r.-1.-1.mca...
Traceback (most recent call last):
  File "test.py", line 144, in <module>
    sys.exit(main(world_folder, start, stop))
  File "test.py", line 115, in main
    process_region_file(region, start, stop)
  File "test.py", line 74, in process_region_file
    cx, cz = c.get_coords()
AttributeError: 'NBTFile' object has no attribute 'get_coords'
```

Is there a way to fix that and/or update it to 1.14.x or anything ? Thanks ^^
